spring:
  datasource:
    url: jdbc:h2:mem:oracle_ucp_spring_boot
    username: sa
    password: ""
    driver-class-name: org.h2.Driver
    type: oracle.ucp.jdbc.PoolDataSource
    oracleucp:
      connection-factory-class-name: org.h2.jdbcx.JdbcDataSource
      connection-pool-name: oracle-ucp-spring-boot-pool
      initial-pool-size: 10
      min-pool-size: 10
      max-pool-size: 10
      sql-for-validate-connection: SELECT 1 FROM DUAL;
      connection-validation-timeout: 3
      query-timeout: 3
  jackson:
    serialization:
      indent-output: true

logging:
  level:
    oracle.ucp: DEBUG

---
spring.config.activate.on-profile: mysql
spring:
  datasource:
    url: jdbc:mysql://localhost/oracle_ucp_spring_boot
    username: root
    password: changeme
    driver-class-name: com.mysql.cj.jdbc.Driver
    oracleucp:
      connection-factory-class-name: com.mysql.cj.jdbc.MysqlDataSource
  sql:
    init:
      mode: always

---
spring.config.activate.on-profile: oracle
spring:
  datasource:
    url: jdbc:mysql:thin:@//localhost:1521/oracle_ucp_spring_boot
    username: root
    password: changeme
    driver-class-name: oracle.jdbc.OracleDriver
    oracleucp:
      connection-factory-class-name: oracle.jdbc.pool.OracleDataSource
  sql:
    init:
      mode: always
